/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementTicker: typeof import('./src/components/AnnouncementTicker.vue')['default']
    ChangeAvatarModal: typeof import('./src/components/profile/ChangeAvatarModal.vue')['default']
    ChangeEmailModal: typeof import('./src/components/profile/ChangeEmailModal.vue')['default']
    ChangePasswordModal: typeof import('./src/components/profile/ChangePasswordModal.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChemicalKeyboard: typeof import('./src/components/ChemicalKeyboard.vue')['default']
    CustomDecks: typeof import('./src/components/profile/CustomDecks.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    DeviceManagementModal: typeof import('./src/components/profile/DeviceManagementModal.vue')['default']
    DuelInviteModal: typeof import('./src/components/DuelInviteModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EquationEditor: typeof import('./src/components/EquationEditor.vue')['default']
    FeedbackButton: typeof import('./src/components/FeedbackButton.vue')['default']
    FeedbackSettings: typeof import('./src/components/FeedbackSettings.vue')['default']
    GameToast: typeof import('./src/components/GameToast.vue')['default']
    HardwareKeyModal: typeof import('./src/components/profile/HardwareKeyModal.vue')['default']
    LevelBadge: typeof import('./src/components/LevelBadge.vue')['default']
    LevelProgress: typeof import('./src/components/LevelProgress.vue')['default']
    LevelUpAnimation: typeof import('./src/components/LevelUpAnimation.vue')['default']
    MatchHistory: typeof import('./src/components/profile/MatchHistory.vue')['default']
    OAuthLogos: typeof import('./src/components/icons/OAuthLogos.vue')['default']
    PersonalSpacePanel: typeof import('./src/components/profile/PersonalSpacePanel.vue')['default']
    PhlogistonIcon: typeof import('./src/components/icons/PhlogistonIcon.vue')['default']
    PingDisplay: typeof import('./src/components/PingDisplay.vue')['default']
    PingIndicator: typeof import('./src/components/PingIndicator.vue')['default']
    ProfileHeader: typeof import('./src/components/profile/ProfileHeader.vue')['default']
    ReactionToast: typeof import('./src/components/ReactionToast.vue')['default']
    ReactionToastDemo: typeof import('./src/components/ReactionToastDemo.vue')['default']
    ResetPassword2FAModal: typeof import('./src/components/ResetPassword2FAModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityPanel: typeof import('./src/components/profile/SecurityPanel.vue')['default']
    SetEmailModal: typeof import('./src/components/profile/SetEmailModal.vue')['default']
    SettingsPanel: typeof import('./src/components/profile/SettingsPanel.vue')['default']
    StatsGrid: typeof import('./src/components/profile/StatsGrid.vue')['default']
    TutorialGuide: typeof import('./src/components/TutorialGuide.vue')['default']
    TwoFactorSetupModal: typeof import('./src/components/profile/TwoFactorSetupModal.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserSpaceModal: typeof import('./src/components/UserSpaceModal.vue')['default']
  }
}
